kind: pipeline
name: default

steps:
  - name: inspect
    image: fpco/stack-build:lts-13
    commands:
      - env
      - pwd
      - ls -al

  - name: hlint
    image: fpco/stack-build:lts-13
    commands:
      - hlint .

  - name: build
    image: fpco/stack-build:lts-13
    commands:
      - stack --local-bin-path dest build --copy-bins --test

  - name: build and upload to dockerhub
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: magthe/ci-test-hs
      tags:
        - "drone-${DRONE_BRANCH}"
        - "drone-${DRONE_BRANCH}-${DRONE_BUILD_NUMBER}"
